name: CI and Release

on:
  push:
    branches:
      - main
    # Fetch full history for semantic versioning
    # (fetch-depth is set in the checkout step)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Allow creating tags and releases
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
